;==============================================================================
; ** source.pb header file by PBHGEN.
;------------------------------------------------------------------------------
;  WARNING: This file is automatically generated each time you save!
;  Any manual changes to this file may be permanently lost upon regeneration.
;  If you came here because of a syntax error, double-check your own code.
;  For more information, visit https://github.com/00laboratories/PBHGEN
;==============================================================================

CompilerIf #PB_Compiler_Module = ""
Declare.i Tabbed(value.i)
Declare.s ManyParameters(first.i,second.i,third.i,fourth.i,fifth.i,sixth.i,seventh.s = "text (inside)",eighth.i = Max(1, 2))
Declare.s QuotedColon(text.s = "a:b")
Declare.s EscapedQuotedColon(text.s = ~"a\":b")
Declare.s CommentColon(text.s = "keep")
Declare.i FirstColon()
Declare.i SecondColon()
CompilerEndIf
