;==============================================================================
; ** source.pb header file by PBHGEN.
;------------------------------------------------------------------------------
;  WARNING: This file is automatically generated each time you save!
;  Any manual changes to this file may be permanently lost upon regeneration.
;  If you came here because of a syntax error, double-check your own code.
;  For more information, visit https://github.com/00laboratories/PBHGEN
;==============================================================================

CompilerIf #PB_Compiler_Module = ""
Declare.s QuotedColon(text.s = "a:b")
Declare.i ManyValues(first.i,second.i,*typed.Model::Value,label.s = ~"escaped \"value:one\"")
CompilerEndIf
CompilerIf #PB_Compiler_Module = "Sample"
Declare Visible(List values.i())
CompilerEndIf
CompilerIf #PB_Compiler_Module = ""
CompilerEndIf
