;==============================================================================
; ** source.pb header file by PBHGEN.
;------------------------------------------------------------------------------
;  WARNING: This file is automatically generated each time you save!
;  Any manual changes to this file may be permanently lost upon regeneration.
;  If you came here because of a syntax error, double-check your own code.
;  For more information, visit https://github.com/00laboratories/PBHGEN
;==============================================================================

CompilerIf #PB_Compiler_Module = ""
Declare.s Escaped(text.s = ~"\"(")
Declare.i AfterEscaped()
CompilerEndIf